#
# Module manifest for module 'cr-devops-azure-core'
#
# Generated by: ryan.phay
#
# Generated on: 03/20/2019
#
# Generated using:  New-ModuleManifest -Path .\cr-devops-azure-core.psd1 -PassThru

@{

   # Script module or binary module file associated with this manifest.
   RootModule           = 'module-template.psm1'

   # Version number of this module.  Don't change, this is automatically modified by the Continuous Integration builds
   ModuleVersion        = '1.0.0'

   # Supported PSEditions
   CompatiblePSEditions = 'Core'

   # ID used to uniquely identify this module
   GUID                 = 'CREATE_COPY_PASTE_A_UNIQUE_GUID_HERE'

   # Author of this module
   Author               = 'ADD_YOUR_EMAIL_ADRESS_HERE'

   # Company or vendor of this module
   CompanyName          = 'CLEAResult'

   # Copyright statement for this module
   Copyright            = '2019 (c) CLEAResult. All rights reserved.'

   # Description of the functionality provided by this module
   Description          = 'ENTER_A_SHORT_DESCRIPTION_OF_THIS_MODULES_PURPOSE'

   # Minimum version of the PowerShell engine required by this module
   PowerShellVersion    = '5.1'

   # Name of the PowerShell host required by this module
   # PowerShellHostName = ''

   # Minimum version of the PowerShell host required by this module
   # PowerShellHostVersion = ''

   # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
   # DotNetFrameworkVersion = ''

   # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
   # CLRVersion = ''

   # Processor architecture (None, X86, Amd64) required by this module
   # ProcessorArchitecture = ''

   # Modules that must be imported into the global environment prior to importing this module
   # RequiredModules = @()

   # Assemblies that must be loaded prior to importing this module
   # RequiredAssemblies = @()

   # Script files (.ps1) that are run in the caller's environment prior to importing this module.
   # ScriptsToProcess = @()

   # Type files (.ps1xml) to be loaded when importing this module
   # TypesToProcess = @()

   # Format files (.ps1xml) to be loaded when importing this module
   # FormatsToProcess = @()

   # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
   # NestedModules = @()

   # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
   FunctionsToExport    = @(
      'ENTER_NAMES_OF',
      'MODULE_FUNCTIONS_TO_EXPORT'
   )

   # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
   CmdletsToExport      = @()

   # Variables to export from this module
   VariablesToExport    = @()

   # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
   AliasesToExport      = @()

   # DSC resources to export from this module
   # DscResourcesToExport = @()

   # List of all modules packaged with this module
   # ModuleList = @()

   # List of all files packaged with this module
   # FileList = @()

   # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
   PrivateData          = @{

      PSData = @{

         # Tags applied to this module. These help with module discovery in online galleries.
         # Tags = @()

         # A URL to the license for this module.
         # LicenseUri = ''

         # A URL to the main website for this project.
         ProjectUri = 'ADD_THE_URI_TO_THE_ GIT_REPO_WHERE_THE_SOURCE_CODE_IS_STORED'

         # A URL to an icon representing this module.
         # IconUri = ''

         # ReleaseNotes of this module
         # ReleaseNotes = ''

      } # End of PSData hashtable

   } # End of PrivateData hashtable

   # HelpInfo URI of this module
   # HelpInfoURI = ''

   # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
   # DefaultCommandPrefix = ''

}

